version: '3.8'

services:
  backend:
    container_name: c_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app/backend
    # command: sh -c "source backend/venv/bin/activate && python backend/app.py"

  postgres:
    image: postgres
    container_name: c_postgres
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=smartFactoryDb

  pgadmin:
    image: dpage/pgadmin4
    container_name: c_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_SERVER: c_postgres
    ports:
      - '80:80'
    depends_on:
      - postgres
